# -*- coding: utf-8 -*-
"""Mckinsey_Project_Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QMzdsCVGLKMB8bhSfkJ5NU5lIwQPvuc

# Mckinsey Dataset Project
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/drive/MyDrive/mckinsey.csv')

#Filter all records where continent is Asia
df[df['continent']=='Asia'].head(11)

# Filter all records for the year 2007.
df[df['year']==2007].head(11)

# Find all recods  where life_exp is greater than 70.
df[df['life_exp']>70].head(11)

# Find countries with gdp_cap greater than 10,000.
df[df['gdp_cap']>10000]['country']

#Filter records where population is more than 100 million.
df[df['population'] > 100000000].head(11)

#Sort the dataset by life_exp in descending order.
df['life_exp'].sort_values(ascending=False).head(11)

#Sort the dataset by gdp_cap in ascending order.
df['gdp_cap'].sort_values(ascending=True).head(11)

#Select only country, year, and life_exp columns.
df[['country','year','life_exp']].head(11)

#Find all records for India.
df[df['country']=='India'].head()

#Find records where continent is either Europe or Asia.
df[~ df['continent'].isin (['Europe','Asia'])].head(11)

#Find the average life expectancy for each continent.
df.groupby('continent')['life_exp'].mean()



#Find total population per continent.
df.groupby('continent')['population'].sum()

#Find the maximum GDP per capita for each continent.
df.groupby('continent')['gdp_cap'].max()

#Find the minimum life expectancy for each year.
df.groupby('life_exp')['year'].max()

#Find average GDP per capita for each year.
df.groupby('gdp_cap')['year'].mean()

#Find the country with highest population in each year.
df.loc[df.groupby('year')['population'].idxmax(),['country','population','year']]

#Count number of records per continent.
df['continent'].value_counts()

#Find top 5 countries with highest life expectancy in 2007.
df[df['year']==2007].sort_values(by='life_exp', ascending=False).head(5)[['country','life_exp']]

#Find bottom 5 countries with lowest GDP per capita in 1952.
df[df['year']==1952].sort_values(by='gdp_cap', ascending=True).head(5)[['country','year','gdp_cap']]



df[df['year']==1952].sort_values('life_exp').head(11)[['year','continent','gdp_cap']]

#Find median life expectancy for each continent.
df.groupby('continent')['life_exp'].median()